<?php
include 'header-sidebar.php';
?>
					<div class="breadcrumbs">Home > All Genre > All</div>
					
					<section class="genres-page clearfix">
						<h3>Search for your favorite music.</h3>
						<div class="faq-link">Need Help? Visit our <a href="#">FAQ Section.</a></div>
						<div class="genres-container">
							<header>
	 							<div class="genres-header">Genres</div>
								<div class="a-z-header">A - Z</div>
								<div class="artist-header">Artist</div>
							</header>
							<section class="genre-filter-container clearfix">
								<div class="genre-column">
									<ul>
										<li><a href="#">All Artists</a></li>
										<li><a href="#">Acapella</a></li>
										<li><a href="#">Acid</a></li>
										<li><a href="#">Acid Jazz</a></li>
										<li><a href="#">Acid Punk</a></li>
										<li><a href="#">Adult Contemporary</a></li>
										<li><a href="#">African</a></li>
										<li><a href="#">Afro Pop</a></li>
										<li><a href="#">Alt-Country</a></li>
										<li><a href="#">Alternative</a></li>
										<li><a href="#">Alternative Rock</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Alternative/Indie</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Blues</a></li>
										<li><a href="#">Christian1</a></li>
										<li><a href="#">Christian2</a></li>
										<li><a href="#">Christian3</a></li>
										<li><a href="#">Christian4</a></li>
										<li><a href="#">Christian5</a></li>
										<li><a href="#">Christian6</a></li>
										<li><a href="#">Christian7</a></li>
										<li><a href="#">Christian8</a></li>
										<li><a href="#">Christian9</a></li>
										<li><a href="#">Christian10</a></li>
										<li><a href="#">Christian11</a></li>
										<li><a href="#">Christian12</a></li>
										<li><a href="#">Christian13</a></li>
										<li><a href="#">Christian14</a></li>
										<li><a href="#">Christian15</a></li>
										<li><a href="#">Christian16</a></li>
										<li><a href="#">Christian17</a></li>
										<li><a href="#">Christian18</a></li>
										<li><a href="#">Christian19</a></li>
										<li><a href="#">Christian20</a></li>
										<li><a href="#">Christian21</a></li>
										<li><a href="#">Christian22</a></li>
										<li><a href="#">Christian23</a></li>
										<li><a href="#">Christian24</a></li>
										<li><a href="#">Christian25</a></li>
										<li><a href="#">Dance1</a></li>
										<li><a href="#">Dance2</a></li>
										<li><a href="#">Dance3</a></li>
										<li><a href="#">Dance4</a></li>
										<li><a href="#">Dance5</a></li>
										<li><a href="#">Dance6</a></li>
										<li><a href="#">Dance7</a></li>
										<li><a href="#">Dance8</a></li>
										<li><a href="#">Dance9</a></li>
										<li><a href="#">Dance10</a></li>
										<li><a href="#">Dance11</a></li>
										<li><a href="#">Dance12</a></li>
										<li><a href="#">Dance13</a></li>
										<li><a href="#">Dance14</a></li>
										<li><a href="#">Dance15</a></li>
										<li><a href="#">Dance16</a></li>
										<li><a href="#">Dance17</a></li>
										<li><a href="#">Dance18</a></li>
										<li><a href="#">Dance19</a></li>
										<li><a href="#">Dance20</a></li>
										<li><a href="#">Dance21</a></li>
										<li><a href="#">Dance22</a></li>
										<li><a href="#">Dance23</a></li>
										<li><a href="#">Dance24</a></li>
										<li><a href="#">Dance25</a></li>
									</ul>
								</div>
								<div class="alpha-artist-list-column">
									<ul>
										<li><a href="#">#</a></li>
										<li><a href="#">ALL</a></li>
										<li><a href="#">A</a></li>
										<li><a href="#">B</a></li>
										<li><a href="#">C</a></li>
										<li><a href="#">D</a></li>
										<li><a href="#">E</a></li>
										<li><a href="#">F</a></li>
										<li><a href="#">G</a></li>
										<li><a href="#">H</a></li>
										<li><a href="#">I</a></li>
										<li><a href="#">J</a></li>
										<li><a href="#">K</a></li>
										<li><a href="#">L</a></li>
										<li><a href="#">M</a></li>
										<li><a href="#">N</a></li>
										<li><a href="#">O</a></li>
										<li><a href="#">P</a></li>
										<li><a href="#">Q</a></li>
										<li><a href="#">R</a></li>
										<li><a href="#">S</a></li>
										<li><a href="#">T</a></li>
										<li><a href="#">U</a></li>
										<li><a href="#">V</a></li>
										<li><a href="#">W</a></li>
										<li><a href="#">X</a></li>
										<li><a href="#">Y</a></li>
										<li><a href="#">Z</a></li>
									</ul>
								</div>
								<div class="artist-column">
									<ul>
										<li><a href="#">Adele</a></li>
										<li><a href="#">Adele</a></li>
										<li><a href="#">Adele</a></li>
										<li><a href="#">Adele</a></li>
										<li><a href="#">Adele</a></li>
										<li><a href="#">Adele</a></li>
										<li><a href="#">Adele</a></li>
										<li><a href="#">Adele</a></li>
										<li><a href="#">Adele</a></li>
										<li><a href="#">Adele</a></li>
										<li><a href="#">Adele</a></li>
										<li><a href="#">Adele</a></li>
										<li><a href="#">Adele</a></li>
										<li><a href="#">Adele</a></li>
										<li><a href="#">Adele</a></li>
										<li><a href="#">Adele</a></li>
										<li><a href="#">Adele</a></li>
										<li><a href="#">Adele</a></li>
										<li><a href="#">Adele</a></li>
										<li><a href="#">Adele</a></li>
										<li><a href="#">Adele</a></li>
										<li><a href="#">Adele</a></li>
										<li><a href="#">Adele</a></li>
										<li><a href="#">Adele</a></li>
										<li><a href="#">Adele</a></li>
										<li><a href="#">Adele</a></li>
										<li><a href="#">Adele</a></li>
										<li><a href="#">Adele</a></li>
										<li><a href="#">Adele</a></li>
										<li><a href="#">Adele</a></li>
										<li><a href="#">Adele</a></li>
										<li><a href="#">Adele</a></li>
										<li><a href="#">Adele</a></li>
										<li><a href="#">Bruno Mars</a></li>
										<li><a href="#">Bruno Mars</a></li>
										<li><a href="#">Bruno Mars</a></li>
										<li><a href="#">Bruno Mars</a></li>
										<li><a href="#">Bruno Mars</a></li>
										<li><a href="#">Bruno Mars</a></li>
										<li><a href="#">Bruno Mars</a></li>
										<li><a href="#">Bruno Mars</a></li>
										<li><a href="#">Bruno Mars</a></li>
										<li><a href="#">Bruno Mars</a></li>
										<li><a href="#">Bruno Mars</a></li>
										<li><a href="#">Bruno Mars</a></li>
										<li><a href="#">Bruno Mars</a></li>
										<li><a href="#">Bruno Mars</a></li>
										<li><a href="#">Bruno Mars</a></li>
										<li><a href="#">Bruno Mars</a></li>
										<li><a href="#">Bruno Mars</a></li>
										<li><a href="#">Coldplay</a></li>
										<li><a href="#">Coldplay</a></li>
										<li><a href="#">Coldplay</a></li>
										<li><a href="#">Coldplay</a></li>
										<li><a href="#">Coldplay</a></li>
										<li><a href="#">Coldplay</a></li>
										<li><a href="#">Coldplay</a></li>
										<li><a href="#">Coldplay</a></li>
										<li><a href="#">Coldplay</a></li>
										<li><a href="#">Coldplay</a></li>
										<li><a href="#">Coldplay</a></li>
										<li><a href="#">Coldplay</a></li>
										<li><a href="#">Coldplay</a></li>
										<li><a href="#">Coldplay</a></li>
										<li><a href="#">Coldplay</a></li>
										<li><a href="#">Coldplay</a></li>
										<li><a href="#">Coldplay</a></li>
										<li><a href="#">Coldplay</a></li>
										<li><a href="#">Coldplay</a></li>
										<li><a href="#">Coldplay</a></li>
										<li><a href="#">Coldplay</a></li>
										<li><a href="#">Coldplay</a></li>
										<li><a href="#">Coldplay</a></li>
										<li><a href="#">Coldplay</a></li>
										<li><a href="#">Coldplay</a></li>
										<li><a href="#">DMB</a></li>
										<li><a href="#">DMB</a></li>
										<li><a href="#">DMB</a></li>
										<li><a href="#">DMB</a></li>
										<li><a href="#">DMB</a></li>
										<li><a href="#">DMB</a></li>
										<li><a href="#">DMB</a></li>
										<li><a href="#">DMB</a></li>
										<li><a href="#">DMB</a></li>
										<li><a href="#">DMB</a></li>
										<li><a href="#">DMB</a></li>
										<li><a href="#">DMB</a></li>
										<li><a href="#">DMB</a></li>
										<li><a href="#">DMB</a></li>
										<li><a href="#">DMB</a></li>
										<li><a href="#">DMB</a></li>
										<li><a href="#">DMB</a></li>
										<li><a href="#">DMB</a></li>
										<li><a href="#">DMB</a></li>
										<li><a href="#">DMB</a></li>
										<li><a href="#">DMB</a></li>
										<li><a href="#">DMB</a></li>
										<li><a href="#">DMB</a></li>
										<li><a href="#">DMB</a></li>
										<li><a href="#">DMB</a></li>
										<li><a href="#">Eminem1</a></li>
										<li><a href="#">Eminem2</a></li>
										<li><a href="#">Eminem3</a></li>
										<li><a href="#">Eminem4</a></li>
										<li><a href="#">Eminem5</a></li>
										<li><a href="#">Eminem6</a></li>
										<li><a href="#">Eminem7</a></li>
										<li><a href="#">Eminem8</a></li>
										<li><a href="#">Eminem9</a></li>
										<li><a href="#">Eminem10</a></li>
										<li><a href="#">Eminem11</a></li>
										<li><a href="#">Eminem12</a></li>
										<li><a href="#">Eminem13</a></li>
										<li><a href="#">Eminem14</a></li>
										<li><a href="#">Eminem15</a></li>
										<li><a href="#">Eminem16</a></li>
										<li><a href="#">Eminem17</a></li>
										<li><a href="#">Eminem18</a></li>
										<li><a href="#">Eminem19</a></li>
										<li><a href="#">Eminem20</a></li>
										<li><a href="#">Eminem21</a></li>
										<li><a href="#">Eminem22</a></li>
										<li><a href="#">Eminem23</a></li>
										<li><a href="#">Eminem24</a></li>
										<li><a href="#">Eminem25</a></li>
										<li><a href="#">Fun1</a></li>
										<li><a href="#">Fun2</a></li>
										<li><a href="#">Fun3</a></li>
										<li><a href="#">Fun4</a></li>
										<li><a href="#">Fun5</a></li>
										<li><a href="#">Fun6</a></li>
										<li><a href="#">Fun7</a></li>
										<li><a href="#">Fun8</a></li>
										<li><a href="#">Fun9</a></li>
										<li><a href="#">Fun10</a></li>
										<li><a href="#">Fun11</a></li>
										<li><a href="#">Fun12</a></li>
										<li><a href="#">Fun13</a></li>
										<li><a href="#">Fun14</a></li>
										<li><a href="#">Fun15</a></li>
										<li><a href="#">Fun16</a></li>
										<li><a href="#">Fun17</a></li>
										<li><a href="#">Fun18</a></li>
										<li><a href="#">Fun19</a></li>
										<li><a href="#">Fun20</a></li>
										<li><a href="#">Fun21</a></li>
										<li><a href="#">Fun22</a></li>
										<li><a href="#">Fun23</a></li>
										<li><a href="#">Fun24</a></li>
										<li><a href="#">Fun25</a></li>
										<li><a href="#">Goo Goo Dolls1</a></li>
										<li><a href="#">Goo Goo Dolls2</a></li>
										<li><a href="#">Goo Goo Dolls3</a></li>
										<li><a href="#">Goo Goo Dolls4</a></li>
										<li><a href="#">Goo Goo Dolls5</a></li>
										<li><a href="#">Goo Goo Dolls6</a></li>
										<li><a href="#">Goo Goo Dolls7</a></li>
										<li><a href="#">Goo Goo Dolls8</a></li>
										<li><a href="#">Goo Goo Dolls9</a></li>
										<li><a href="#">Goo Goo Dolls10</a></li>
										<li><a href="#">Goo Goo Dolls11</a></li>
										<li><a href="#">Goo Goo Dolls12</a></li>
										<li><a href="#">Goo Goo Dolls13</a></li>
										<li><a href="#">Goo Goo Dolls14</a></li>
										<li><a href="#">Goo Goo Dolls15</a></li>
										<li><a href="#">Goo Goo Dolls16</a></li>
										<li><a href="#">Goo Goo Dolls17</a></li>
										<li><a href="#">Goo Goo Dolls18</a></li>
										<li><a href="#">Goo Goo Dolls19</a></li>
										<li><a href="#">Goo Goo Dolls20</a></li>
										<li><a href="#">Goo Goo Dolls21</a></li>
										<li><a href="#">Goo Goo Dolls22</a></li>
										<li><a href="#">Goo Goo Dolls23</a></li>
										<li><a href="#">Goo Goo Dolls24</a></li>
										<li><a href="#">Goo Goo Dolls25</a></li>
										<li><a href="#">Hootie1</a></li>
										<li><a href="#">Hootie2</a></li>
										<li><a href="#">Hootie3</a></li>
										<li><a href="#">Hootie4</a></li>
										<li><a href="#">Hootie5</a></li>
										<li><a href="#">Hootie6</a></li>
										<li><a href="#">Hootie7</a></li>
										<li><a href="#">Hootie8</a></li>
										<li><a href="#">Hootie9</a></li>
										<li><a href="#">Hootie10</a></li>
										<li><a href="#">Hootie11</a></li>
										<li><a href="#">Hootie12</a></li>
										<li><a href="#">Hootie13</a></li>
										<li><a href="#">Hootie14</a></li>
										<li><a href="#">Hootie15</a></li>
										<li><a href="#">Hootie16</a></li>
										<li><a href="#">Hootie17</a></li>
										<li><a href="#">Hootie18</a></li>
										<li><a href="#">Hootie19</a></li>
										<li><a href="#">Hootie20</a></li>
										<li><a href="#">Hootie21</a></li>
										<li><a href="#">Hootie22</a></li>
										<li><a href="#">Hootie23</a></li>
										<li><a href="#">Hootie24</a></li>
										<li><a href="#">Hootie25</a></li>
										<li><a href="#">Lorde1</a></li>
										<li><a href="#">Lorde2</a></li>
										<li><a href="#">Lorde3</a></li>
										<li><a href="#">Lorde4</a></li>
										<li><a href="#">Lorde5</a></li>
										<li><a href="#">Lorde6</a></li>
										<li><a href="#">Lorde7</a></li>
										<li><a href="#">Lorde8</a></li>
										<li><a href="#">Lorde9</a></li>
										<li><a href="#">Lorde10</a></li>
										<li><a href="#">Lorde11</a></li>
										<li><a href="#">Lorde12</a></li>
										<li><a href="#">Lorde13</a></li>
										<li><a href="#">Lorde14</a></li>
										<li><a href="#">Lorde15</a></li>
										<li><a href="#">Lorde16</a></li>
										<li><a href="#">Lorde17</a></li>
										<li><a href="#">Lorde18</a></li>
										<li><a href="#">Lorde19</a></li>
										<li><a href="#">Lorde20</a></li>
										<li><a href="#">Lorde21</a></li>
										<li><a href="#">Lorde22</a></li>
										<li><a href="#">Lorde23</a></li>
										<li><a href="#">Lorde24</a></li>
										<li><a href="#">Lorde25</a></li>
										<li><a href="#">Miley Cyrus1</a></li>
										<li><a href="#">Miley Cyrus2</a></li>
										<li><a href="#">Miley Cyrus3</a></li>
										<li><a href="#">Miley Cyrus4</a></li>
										<li><a href="#">Miley Cyrus5</a></li>
										<li><a href="#">Miley Cyrus6</a></li>
										<li><a href="#">Miley Cyrus7</a></li>
										<li><a href="#">Miley Cyrus8</a></li>
										<li><a href="#">Miley Cyrus9</a></li>
										<li><a href="#">Miley Cyrus10</a></li>
										<li><a href="#">Miley Cyrus11</a></li>
										<li><a href="#">Miley Cyrus12</a></li>
										<li><a href="#">Miley Cyrus13</a></li>
										<li><a href="#">Miley Cyrus14</a></li>
										<li><a href="#">Miley Cyrus15</a></li>
										<li><a href="#">Miley Cyrus16</a></li>
										<li><a href="#">Miley Cyrus17</a></li>
										<li><a href="#">Miley Cyrus18</a></li>
										<li><a href="#">Miley Cyrus19</a></li>
										<li><a href="#">Miley Cyrus20</a></li>
										<li><a href="#">Miley Cyrus21</a></li>
										<li><a href="#">Miley Cyrus22</a></li>
										<li><a href="#">Miley Cyrus23</a></li>
										<li><a href="#">Miley Cyrus24</a></li>
										<li><a href="#">Miley Cyrus25</a></li>
										<li><a href="#">Ne-Yo1</a></li>
										<li><a href="#">Ne-Yo2</a></li>
										<li><a href="#">Ne-Yo3</a></li>
										<li><a href="#">Ne-Yo4</a></li>
										<li><a href="#">Ne-Yo5</a></li>
										<li><a href="#">Ne-Yo6</a></li>
										<li><a href="#">Ne-Yo7</a></li>
										<li><a href="#">Ne-Yo8</a></li>
										<li><a href="#">Ne-Yo9</a></li>
										<li><a href="#">Ne-Yo10</a></li>
										<li><a href="#">Ne-Yo11</a></li>
										<li><a href="#">Ne-Yo12</a></li>
										<li><a href="#">Ne-Yo13</a></li>
										<li><a href="#">Ne-Yo14</a></li>
										<li><a href="#">Ne-Yo15</a></li>
										<li><a href="#">Ne-Yo16</a></li>
										<li><a href="#">Ne-Yo17</a></li>
										<li><a href="#">Ne-Yo18</a></li>
										<li><a href="#">Ne-Yo19</a></li>
										<li><a href="#">Ne-Yo20</a></li>
										<li><a href="#">Ne-Yo21</a></li>
										<li><a href="#">Ne-Yo22</a></li>
										<li><a href="#">Ne-Yo23</a></li>
										<li><a href="#">Ne-Yo24</a></li>
										<li><a href="#">Ne-Yo25</a></li>
										<li><a href="#">One Republic1</a></li>
										<li><a href="#">One Republic2</a></li>
										<li><a href="#">One Republic3</a></li>
										<li><a href="#">One Republic4</a></li>
										<li><a href="#">One Republic5</a></li>
										<li><a href="#">One Republic6</a></li>
										<li><a href="#">One Republic7</a></li>
										<li><a href="#">One Republic8</a></li>
										<li><a href="#">One Republic9</a></li>
										<li><a href="#">One Republic10</a></li>
										<li><a href="#">One Republic11</a></li>
										<li><a href="#">One Republic12</a></li>
										<li><a href="#">One Republic13</a></li>
										<li><a href="#">One Republic14</a></li>
										<li><a href="#">One Republic15</a></li>
										<li><a href="#">One Republic16</a></li>
										<li><a href="#">One Republic17</a></li>
										<li><a href="#">One Republic18</a></li>
										<li><a href="#">One Republic19</a></li>
										<li><a href="#">One Republic20</a></li>
										<li><a href="#">One Republic21</a></li>
										<li><a href="#">One Republic22</a></li>
										<li><a href="#">One Republic23</a></li>
										<li><a href="#">One Republic24</a></li>
										<li><a href="#">One Republic25</a></li>

									</ul>
								</div>

							</div>
							<div class="genre-button-container">
								<button class="genre-scroll-up"></button>
								<button class="genre-scroll-down"></button>
								<button class="artist-scroll-up"></button>
								<button class="artist-scroll-down"></button>
							</div>
						</section>

					</section>


<?php
include 'footer.php';
?>